name: Test CloudFormation Validation Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  test-valid-templates:
    name: Test Valid CloudFormation Templates
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
          role-session-name: cloudformation-validation-${{ github.run_id }}
          aws-region: us-east-1
        continue-on-error: true

      - name: Test valid template with parameters
        uses: ./
        with:
          cloudformation-dir: 'tests/fixtures/valid-templates'
          template-file: 'template.yaml'
          parameters-file: 'parameters.json'
          aws-region: 'us-east-1'
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
        continue-on-error: true
        id: valid-test

      - name: Verify valid template test results
        run: |
          echo "Validation result: ${{ steps.valid-test.outputs.validation-result }}"
          echo "Main template result: ${{ steps.valid-test.outputs.main-template-result }}"
          echo "Nested templates result: ${{ steps.valid-test.outputs.nested-templates-result }}"
          echo "Parameters result: ${{ steps.valid-test.outputs.parameters-result }}"
          
          # For testing purposes, we expect this to work in a real AWS environment
          # In CI without AWS credentials, we expect it to fail with auth errors
          if [[ "${{ steps.valid-test.outputs.main-template-result }}" == "success" ]]; then
            echo "✅ Valid template test passed as expected"
          else
            echo "ℹ️ Valid template test failed (likely due to missing AWS credentials in CI)"
          fi

  test-invalid-templates:
    name: Test Invalid CloudFormation Templates
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
          role-session-name: cloudformation-validation-${{ github.run_id }}
          aws-region: us-east-1
        continue-on-error: true

      - name: Test invalid template syntax
        uses: ./
        with:
          cloudformation-dir: 'tests/fixtures/invalid-templates'
          template-file: 'syntax-error.yaml'
          aws-region: 'us-east-1'
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
        continue-on-error: true
        id: invalid-syntax-test

      - name: Verify invalid template test results
        run: |
          echo "Validation result: ${{ steps.invalid-syntax-test.outputs.validation-result }}"
          echo "Main template result: ${{ steps.invalid-syntax-test.outputs.main-template-result }}"
          
          # We expect this to fail due to syntax errors
          if [[ "${{ steps.invalid-syntax-test.outputs.main-template-result }}" == "failure" ]]; then
            echo "✅ Invalid template test failed as expected"
          else
            echo "⚠️ Invalid template test did not fail as expected"
          fi

      - name: Test missing template file
        uses: ./
        with:
          cloudformation-dir: 'tests/fixtures/invalid-templates'
          template-file: 'nonexistent.yaml'
          aws-region: 'us-east-1'
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
        continue-on-error: true
        id: missing-file-test

      - name: Verify missing file test results
        run: |
          echo "Validation result: ${{ steps.missing-file-test.outputs.validation-result }}"
          echo "Main template result: ${{ steps.missing-file-test.outputs.main-template-result }}"
          
          # We expect this to fail due to missing file
          if [[ "${{ steps.missing-file-test.outputs.main-template-result }}" == "failure" ]]; then
            echo "✅ Missing file test failed as expected"
          else
            echo "⚠️ Missing file test did not fail as expected"
          fi

  test-nested-templates:
    name: Test Nested Templates Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
          role-session-name: cloudformation-validation-${{ github.run_id }}
          aws-region: us-east-1
        continue-on-error: true

      - name: Test valid nested templates
        uses: ./
        with:
          cloudformation-dir: 'tests/fixtures/nested-templates'
          template-file: 'main-template.yaml'
          aws-region: 'us-east-1'
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
        continue-on-error: true
        id: nested-valid-test

      - name: Verify nested templates test results
        run: |
          echo "Validation result: ${{ steps.nested-valid-test.outputs.validation-result }}"
          echo "Main template result: ${{ steps.nested-valid-test.outputs.main-template-result }}"
          echo "Nested templates result: ${{ steps.nested-valid-test.outputs.nested-templates-result }}"
          
          # In a real AWS environment, we expect nested validation to run
          # In CI without credentials, main template validation will fail first
          echo "ℹ️ Nested templates test completed (results depend on AWS credentials)"

      - name: Test mixed valid/invalid nested templates
        uses: ./
        with:
          cloudformation-dir: 'tests/fixtures/mixed-nested-templates'
          template-file: 'main-template.yaml'
          aws-region: 'us-east-1'
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
        continue-on-error: true
        id: mixed-nested-test

      - name: Verify mixed nested templates test results
        run: |
          echo "Validation result: ${{ steps.mixed-nested-test.outputs.validation-result }}"
          echo "Main template result: ${{ steps.mixed-nested-test.outputs.main-template-result }}"
          echo "Nested templates result: ${{ steps.mixed-nested-test.outputs.nested-templates-result }}"
          
          echo "ℹ️ Mixed nested templates test completed"

  test-parameters-validation:
    name: Test Parameters File Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
          role-session-name: cloudformation-validation-${{ github.run_id }}
          aws-region: us-east-1
        continue-on-error: true

      - name: Test valid parameters file
        uses: ./
        with:
          cloudformation-dir: 'tests/fixtures/valid-parameters'
          template-file: 'template.yaml'
          parameters-file: 'parameters.json'
          aws-region: 'us-east-1'
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
        continue-on-error: true
        id: valid-params-test

      - name: Verify valid parameters test results
        run: |
          echo "Validation result: ${{ steps.valid-params-test.outputs.validation-result }}"
          echo "Parameters result: ${{ steps.valid-params-test.outputs.parameters-result }}"
          
          echo "ℹ️ Valid parameters test completed"

      - name: Test invalid parameters file
        uses: ./
        with:
          cloudformation-dir: 'tests/fixtures/invalid-parameters'
          template-file: 'template.yaml'
          parameters-file: 'invalid-parameters.json'
          aws-region: 'us-east-1'
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
        continue-on-error: true
        id: invalid-params-test

      - name: Verify invalid parameters test results
        run: |
          echo "Validation result: ${{ steps.invalid-params-test.outputs.validation-result }}"
          echo "Parameters result: ${{ steps.invalid-params-test.outputs.parameters-result }}"
          
          echo "ℹ️ Invalid parameters test completed"

      - name: Test missing parameters file (should skip)
        uses: ./
        with:
          cloudformation-dir: 'tests/fixtures/no-parameters'
          template-file: 'template.yaml'
          parameters-file: 'nonexistent.json'
          aws-region: 'us-east-1'
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
        continue-on-error: true
        id: missing-params-test

      - name: Verify missing parameters test results
        run: |
          echo "Validation result: ${{ steps.missing-params-test.outputs.validation-result }}"
          echo "Parameters result: ${{ steps.missing-params-test.outputs.parameters-result }}"
          
          # Parameters validation should be skipped when file doesn't exist
          if [[ "${{ steps.missing-params-test.outputs.parameters-result }}" == "skipped" ]]; then
            echo "✅ Missing parameters test skipped as expected"
          else
            echo "ℹ️ Missing parameters test result: ${{ steps.missing-params-test.outputs.parameters-result }}"
          fi

  test-edge-cases:
    name: Test Edge Cases
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
          role-session-name: cloudformation-validation-${{ github.run_id }}
          aws-region: us-east-1
        continue-on-error: true

      - name: Test empty template file
        uses: ./
        with:
          cloudformation-dir: 'tests/fixtures/edge-cases'
          template-file: 'empty-template.yaml'
          aws-region: 'us-east-1'
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
        continue-on-error: true
        id: empty-template-test

      - name: Verify empty template test results
        run: |
          echo "Validation result: ${{ steps.empty-template-test.outputs.validation-result }}"
          echo "Main template result: ${{ steps.empty-template-test.outputs.main-template-result }}"
          
          # Empty template should fail
          if [[ "${{ steps.empty-template-test.outputs.main-template-result }}" == "failure" ]]; then
            echo "✅ Empty template test failed as expected"
          else
            echo "⚠️ Empty template test did not fail as expected"
          fi

      - name: Test nonexistent directory
        uses: ./
        with:
          cloudformation-dir: 'tests/fixtures/nonexistent-directory'
          template-file: 'template.yaml'
          aws-region: 'us-east-1'
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN || 'arn:aws:iam::123456789012:role/test-role' }}
        continue-on-error: true
        id: nonexistent-dir-test

      - name: Verify nonexistent directory test results
        run: |
          echo "Validation result: ${{ steps.nonexistent-dir-test.outputs.validation-result }}"
          echo "Main template result: ${{ steps.nonexistent-dir-test.outputs.main-template-result }}"
          
          # Nonexistent directory should fail
          if [[ "${{ steps.nonexistent-dir-test.outputs.main-template-result }}" == "failure" ]]; then
            echo "✅ Nonexistent directory test failed as expected"
          else
            echo "⚠️ Nonexistent directory test did not fail as expected"
          fi

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [test-valid-templates, test-invalid-templates, test-nested-templates, test-parameters-validation, test-edge-cases]
    if: always()
    
    steps:
      - name: Test Results Summary
        run: |
          echo "## CloudFormation Validation Action Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Test Category | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|---------------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Valid Templates | ${{ needs.test-valid-templates.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Invalid Templates | ${{ needs.test-invalid-templates.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Nested Templates | ${{ needs.test-nested-templates.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Parameters Validation | ${{ needs.test-parameters-validation.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Edge Cases | ${{ needs.test-edge-cases.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Notes" >> $GITHUB_STEP_SUMMARY
          echo "- Tests may fail in CI environments without proper AWS credentials" >> $GITHUB_STEP_SUMMARY
          echo "- This is expected behavior and validates the action's error handling" >> $GITHUB_STEP_SUMMARY
          echo "- For full testing, run with valid AWS credentials and IAM role" >> $GITHUB_STEP_SUMMARY